### ISSUE TITLE
Code and data for KITTI dataset

### ISSUE THREAD

**Issue by ZhiChen902** [Gardlin/PEAL#4]
Thank you for your nice work!

Will you release the prior data and code for the KITTI dataset?

**Comment by Gardlin** [comment]
Based on our experiments, we've observed that performance on the KITTI dataset is approaching saturation. Compared to GeoTransformer, our approach only shows marginal improvements, with only slight enhancements in the rre/rte metric. However, we have seen significant improvements in the performance of our model on the ModelNet40 dataset. We plan to release the code for this soon.
